version: '3.7'

services:
  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    ports: 
      - "6379:6379"
    networks:
      - base_network
    command: redis-server --appendonly yes
    volumes: 
      - cache:/data

  database:
    image: mysql:8.0.26
    container_name: database
    restart: always
    ports: 
      - "3306:3306"
    networks:
      - base_network
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=base
      - MYSQL_USER=base
      - MYSQL_PASSWORD=password
      
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports: 
      - "8080:8080"
    networks:
      - base_network
    depends_on:
      - database

  api:
    environment: 
      - REDIS_HOST=redis
      - DB_HOST=database
    build:
      dockerfile: api.dockerfile
      context: .
    image: api:v1
    container_name: api
    ports:
      - "3030:3030"
    networks:
      - base_network
    command: npm start
    depends_on: 
      - redis
      - database

networks:
  base_network:
    driver: bridge

volumes: 
  cache: